# Railway Build Configuration
# This file tells Railway how to build Laravel properly

[build]
builder = "nixpacks"

[build.env]
NODE_VERSION = "18"
PHP_VERSION = "8.1"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
restartPolicyType = "always"
